### ISSUE TITLE
ServerlessError: No file matches include / exclude patterns when using Layers

### ISSUE THREAD

**Issue by WeaponizedLego** [serverless/serverless-plugin-typescript#240]
Im experiencing No FIle Matches include / exclude patterns when using the new AWS Lambda layers 

here is the last part of the logs

```
serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
 
 Serverless Error ----------------------------------------
 
  ServerlessError: No file matches include / exclude patterns
      at /Users/glen/_code/ts-ooono-backend/node_modules/serverless/lib/plugins/package/lib/packageService.js:263:13
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /Users/glen/_code/ts-ooono-backend/node_modules/serverless/lib/plugins/package/lib/packageService.js:91:9
      at async Promise.all (index 2)
      at async Package.packageService (/Users/glen/_code/ts-ooono-backend/node_modules/serverless/lib/plugins/package/lib/packageService.js:95:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              16.0.0
     Framework Version:         2.47.0 (local)
     Plugin Version:            5.4.0
     SDK Version:               4.2.3
     Components Version:        3.12.0

```
and this is my layers and plugins

```
##
## Package settings
##
package:
  excludeDevDependencies: true
  individually: true
  patterns:
    - '!node_modules'
    - '!layers'

##
## Serverless plugins
## TODO: figure out how to have serverless-plugin-typescript in and still deploy as it doesn't build without it
plugins:
  - serverless-plugin-typescript
  - serverless-offline

##
## Layers
##
layers:
  NodeModules:
    path: layers
#    name: NodeModules
    name: ${sls:stage}-NodeModules
    compatibleRuntimes:
      - nodejs14.x
    package:
      patterns:
        - '**/**'
    description: ---
    retain: false # Delete layers once a new one of same name is uploaded

##
## FUNCTIONS
##
functions:
  # GET /hello
  hello:
    handler: ./src/functions/helloworld/index.handler
    events: # The events that trigger this function
      - http:
          path: ts-ooonoBackend/helloworld
          method: get
    layers:
      - { Ref: NodeModulesLambdaLayer }
    package:
      patterns:
        - 'src/functions/helloworld/**'
  goodbye:
    handler: ./src/functions/goodbye/index.handler
    events: # The events that trigger this function
      - http:
          path: ts-ooonoBackend/goodbye
          method: post
    layers:
      - { Ref: NodeModulesLambdaLayer }
    package:
      patterns:
        - 'src/functions/goodbye/**'
```

**Comment by medikoo** [comment]
Will be fixed with #243

**Comment by pgrzesik** [comment]
After doing research as part of https://github.com/serverless/serverless/issues/9873 I've realised that layers are generally not supported by this plugin so this issue should still be open.

**Comment by abdullahmonoar** [comment]
@pgrzesik any workarounds you know of other than webpacking the ts files ourselves?

**Comment by pgrzesik** [comment]
Hello @abdullahmonoar - the only workaround I know is switching to `serverless-webpack` or `serverless-jetpack` :(

**Comment by alexandrubese** [comment]
I can also confirm it works by using serverless-jetpack

**Comment by raiseandfall** [comment]
@medikoo this looks old, but that seems to be addressing the issue: https://github.com/serverless/serverless-plugin-typescript/pull/128

**Comment by mmeyers-xomly** [comment]
Since there wasn't any movement on this from the original author, I updated https://github.com/serverless/serverless-plugin-typescript/pull/128 and submitted it again which fixes this issue https://github.com/serverless/serverless-plugin-typescript/pull/267

**Comment by mmeyers-xomly** [comment]
So the above PR fixes part of the issue, but not fully. It seems this only helps if the thing you want to put in a layer is something that would be packaged by this plugin. However, if it's an external file that wouldn't be included in the TS build, this is still broken with the same error.

**Comment by micheleangioni** [comment]
We've also been hit by this problem, any update?

**Comment by alexandrubese** [comment]
This is still a problem

**Comment by tachang** [comment]
> So the above PR fixes part of the issue, but not fully. It seems this only helps if the thing you want to put in a layer is something that would be packaged by this plugin. However, if it's an external file that wouldn't be included in the TS build, this is still broken with the same error.

I just ran into this and feel like it the commit needs to be reverted. I'm not sure exactly what case allows it to succeed. Is it checking for patterns: include because that is deprecated in serverless v3.

**Comment by leonardoviada** [comment]
@tachang any clue on how to tackle the problem in some way?
I have a module in `src/layer/shared/nodejs/node_modules/myd-api-utils/src/index.ts`
Locally everything works just fine but I cannot deploy it since it breaks during the CI process

**Comment by walshe** [comment]
> @tachang any clue on how to tackle the problem in some way? I have a module in `src/layer/shared/nodejs/node_modules/myd-api-utils/src/index.ts` Locally everything works just fine but I cannot deploy it since it breaks during the CI process

same here

**Comment by tttaisgt** [comment]
<img width="323" alt="image" src="https://github.com/serverless/serverless-plugin-typescript/assets/68092893/b45f23a1-065f-4d77-95ba-b7e503da32a6">
the error still there 😢

**Comment by cwbuecheler** [comment]
Still seeing this error as of January 2024. Take the layer out of serverless.yml and the plugin works fine. Put the layer back in, and I get the same error reported above. Layer code in the YML looks like this:

```
layers:
  shared:
    name: hcapps-file-xfer-shared
    path: layers/shared
    description: Shared functionality for file transfer system
    compatibleRuntimes:
      - nodejs18.x
    compatibleArchitectures:
      - x86_64
    retain: false
```
I don't see anything in here that should be considered weird.

We've written our own build system for using TS with serverless but I was really hoping to ditch that and use the plugin. We make extensive use of shared layers though, so this is kind of important. I'll admit I could be screwing something up, but at this point I feel like I've tried every reasonable config option (and again, it works fine with the functions - it's just the layer that breaks)

Edit to add: there is nothing in `/layers` except a file called `shared.ts`
