### ISSUE TITLE
Adding plugin prevents deployment

### ISSUE THREAD

**Issue by Oldbury** [serverless/serverless-plugin-typescript#262]
### Issue
When adding plugin to Serverless it prevents the deployment from completing. This issue occurs with `Serverless-plugin-typescript` and `serverless-esbuild`

### Serverless.yml

```
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  httpApi:
    cors: true

custom:
  esbuild:
    packager: yarn

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-monorepo
  - serverless-offline
  # - serverless-esbuild
  # - serverless-prune-plugin

functions:
  get-user:
    handler: "./modules/users/get/handler.GetUser"
    events:
      - httpApi:
          path: /users/{userId}
          method: GET
  create-user:
    handler: "./modules/users/create/handler.CreateUser"
    events:
      - httpApi:
          path: /users
          method: POST
```

### Package.json
```
{
  "name": "apis",
  "version": "1.0.0",
  "license": "MIT",
  "dependencies": {
    "@types/node": "^17.0.8",
    "config": "*",
    "serverless-esbuild": "^1.23.3",
    "serverless-offline": "^8.3.1",
    "serverless-plugin-monorepo": "^0.11.0",
    "serverless-plugin-typescript": "^2.1.0",
    "serverless-prune-plugin": "^2.0.1",
    "typescript": "^4.5.4",
    "esbuild": "^0.14.11"
  }
}
```

### Output

```
➜  apis git:(main) ✗ sls deploy
simple-git deprecation notice: git.silent: logging should be configured using the `debug` library / `DEBUG` environment variable, this will be an error in version 3
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Cleaning dependency symlinks
Serverless: Creating dependency symlinks
Serverless: Compiling to node12 bundle with esbuild...
Serverless: Compiling with concurrency: Infinity
Serverless: Compiling completed.

```

### Expected Result
Functions deploy as usual, which was happening before adding the typescript plugin
