### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by mdrijwan** [serverless/serverless-plugin-typescript#280]
i'm trying to deploy docker image through sls

```
functions:
  generatePdf:
    # handler: src/api/generate.pdf
    images: 498157479666.dkr.ecr.ap-southeast-1.amazonaws.com/automate-pdf:latest@sha256:98e17f123e538564dff238122cc31ab38ddf1e735e4cc5f7be853cc2cc5e1dee
    description: A lambda handler that generates PDF file from payload data and upload it to S3 bucket.
    memorySize: 2048
    provisionedConcurrency: 2
    events:
      - http:
          path: pdf
          method: POST
          cors: true
          documentation:
            summary: Generates PDF from payload
            tags:
              - generatePdfS3
```

it works perfectly with `handler` but the moment i switch to `images`, it throws this weird error

```
TypeError: Cannot read properties of undefined (reading 'split')
    at /Users/rijwan/code/second/automate-pdf-api/node_modules/serverless-plugin-typescript/dist/src/typescript.js:57:33
    at Array.map (<anonymous>)
```
![Screenshot 2022-09-13 at 12 01 31 AM](https://user-images.githubusercontent.com/22044931/189701509-3446bf65-1987-4993-a34e-2744ef083db3.png)

my sls version is as below:

```
Framework Core: 3.22.0
Plugin: 6.2.2
SDK: 4.3.2
```
