### ISSUE TITLE
Using multiple runtimes and explicit artifact, receive Cannot access package artifact error

### ISSUE THREAD

**Issue by vectorjohn** [serverless/serverless-plugin-typescript#281]
Hard to describe, but this is when using multiple runtimes, and the other runtime has manual packaging. So we use the `package.artifact` configuration in serverless.yml, e.g.:
```
functions:
  hello:
    handler: com.serverless.Handler
    package:
      artifact: target/hello-dev.jar
```

When I try to package or deploy (e.g. `sls deploy`), after compiling the typescript it fails with this error:
```
Error:
Cannot access package artifact at "target/hello-dev.jar" (for "hello"): ENOENT: no such file or directory, access '[REDACTED]/serverless-packaging-bug/.build/target/hello-dev.jar'
```

This seems to be caused by the code in `index.ts` in the `compileTs` function, with this line:
`this.serverless.config.servicePath = path.join(this.originalServicePath, BUILD_FOLDER)`

Since this doesn't get cleaned up until the very end, it messes with other parts of the serverless build process. That path seems to be where serverless looks for my `artifact`. 

For reference:
`Environment: linux, node 14.19.3, framework 3.22.0 (local) 3.22.0v (global), plugin 6.2.2, SDK 4.3.2`

This exact serverless.yml used to work in Serverless v2 so perhaps they changed something, but from what I can tell the bug still lies in this plugin.

Here is a full serverless.yml for testing:
```
service: serverless-packaging-bug

plugins:
  - serverless-plugin-typescript

frameworkVersion: '3'

provider:
  name: aws
  runtime: java8

package:
  individually: true

functions:
  hello:
    handler: com.serverless.Handler
    package:
      artifact: target/hello-dev.jar

  cool:
    runtime: nodejs16.x
    handler: js/cool.handler
    events:
      - http:
          path: cool
          method: get
```
