### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find module

### ISSUE THREAD

**Issue by Strydom** [serverless/serverless-plugin-typescript#288]
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../apps/api/.build/src/app' imported from .../apps/api/.build/src/lambda.js
```

```
root/apps/api
- /src
  - app.ts // exports the express app
  - lambda.ts
  - server.ts // used to run normal express server
- package.json
- serverless.yml
- tsconfig.json
```

lambda.ts/js
```js
import serverless from "serverless-http";
import { app } from "./app";
export const handler = serverless(app);
```

app.ts/js
```js
// express setup
...
export { app };
```

tsconfig.json
```json
{
  "compilerOptions": {
    "lib": ["ESNext"],
    "module": "ESNext",
    "target": "ESNext",
    "moduleResolution": "Node",
    "esModuleInterop": true,
    "outDir": "dist",
    "baseUrl": ".",
    "strict": true,
    "noImplicitAny": true,
    "resolveJsonModule": true
  },
  "ts-node": {
    "esm": true,
    "experimentalSpecifierResolution": "node"
  },
  "include": [
    "src/**/*"
  ]
}
```

serverless.yml
```
service: api
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi: '*'
```

Running with `ts-node` works perfectly 🤷🏻‍♂️
